export const products = [
	{ id: 1, name: "Майонез Провансаль", brand: "Чумак", quantity: 12 },
	{ id: 2, name: "Йогурт Полуничний", brand: "Галичина", quantity: 8 },
	{ id: 3, name: "Чай Зелений", brand: "Lipton", quantity: 23 },
	{ id: 4, name: "Сік Апельсиновий", brand: "Сандора", quantity: 17 },
	{ id: 5, name: "Кетчуп Гострий", brand: "Торчин", quantity: 5 },
	{ id: 6, name: "Хліб Житній", brand: "Київхліб", quantity: 15 },
	{ id: 7, name: "Сир Голландський", brand: "Комо", quantity: 10 },
	{ id: 8, name: "Макарони Спіралі", brand: "Щедро", quantity: 20 },
	{ id: 9, name: "Пельмені Домашні", brand: "Геркулес", quantity: 7 },
	{ id: 10, name: "Молоко 2.5%", brand: "Простоквашино", quantity: 13 },
	{ id: 11, name: "Майонез Оливковий", brand: "Торчин", quantity: 9 },
	{ id: 12, name: "Йогурт Персиковий", brand: "Галичина", quantity: 11 },
	{ id: 13, name: "Чай Чорний", brand: "Greenfield", quantity: 14 },
	{ id: 14, name: "Сік Вишневий", brand: "Сандора", quantity: 22 },
	{ id: 15, name: "Кетчуп Лагідний", brand: "Чумак", quantity: 6 },
	{ id: 16, name: "Хліб Пшеничний", brand: "Київхліб", quantity: 16 },
	{ id: 17, name: "Сир Російський", brand: "Звенигора", quantity: 10 },
	{ id: 18, name: "Макарони Ріжки", brand: "Щедро", quantity: 19 },
	{ id: 19, name: "Пельмені Сибірські", brand: "Геркулес", quantity: 12 },
	{ id: 20, name: "Молоко 1%", brand: "Яготинське", quantity: 14 },
	{ id: 21, name: "Олія Соняшникова", brand: "Олейна", quantity: 18 },
	{ id: 22, name: "Олія Рафінована", brand: "Щедрий Дар", quantity: 13 },
	{ id: 23, name: "Шоколад Молочний", brand: "Корона", quantity: 7 },
	{ id: 24, name: "Шоколад Чорний", brand: "Мілка", quantity: 6 },
	{ id: 25, name: "Чіпси Солоні", brand: "Lays", quantity: 15 },
	{ id: 26, name: "Чіпси Паприка", brand: "Lux", quantity: 10 },
	{ id: 27, name: "Туалетний папір 4 шари", brand: "Zewa", quantity: 20 },
	{ id: 28, name: "Туалетний папір 2 шари", brand: "Обухів", quantity: 18 },
	{ id: 29, name: "Ковбаса Салямі", brand: "Глобино", quantity: 14 },
	{ id: 30, name: "Ковбаса Лікарська", brand: "Ятрань", quantity: 11 },
	{ id: 31, name: "Печиво Овсяне", brand: "Рошен", quantity: 9 },
	{ id: 32, name: "Печиво Шоколадне", brand: "Рошен", quantity: 7 },
	{ id: 33, name: "Кава Мелена", brand: "Jacobs", quantity: 13 },
	{ id: 34, name: "Кава Розчинна", brand: "Nescafe", quantity: 10 },
	{ id: 35, name: "Цукор Білий", brand: "Україна", quantity: 25 },
	{ id: 36, name: "Сіль Кам’яна", brand: "Артемсіль", quantity: 28 },
	{ id: 37, name: "Мінеральна Вода", brand: "Моршинська", quantity: 30 },
	{ id: 38, name: "Газована Вода", brand: "Боржомі", quantity: 19 },
	{ id: 39, name: "Рис Шліфований", brand: "Національ", quantity: 21 },
	{ id: 40, name: "Гречка Ядриця", brand: "Хуторок", quantity: 22 },
	{ id: 41, name: "Кукурудзяні палички", brand: "Клуб 4 лапи", quantity: 9 },
	{ id: 42, name: "Сир Плавлений", brand: "Весела Корівка", quantity: 12 },
	{ id: 43, name: "Йогурт Натуральний", brand: "Галичина", quantity: 7 },
	{ id: 44, name: "Масло Селянське", brand: "Ферма", quantity: 10 },
	{ id: 45, name: "Сметана 20%", brand: "Простоквашино", quantity: 14 },
	{ id: 46, name: "Кефір 1%", brand: "Яготинське", quantity: 16 },
	{ id: 47, name: "Майонез Домашній", brand: "Чумак", quantity: 11 },
	{ id: 48, name: "Пельмені Класичні", brand: "Геркулес", quantity: 13 },
	{ id: 49, name: "Чіпси Сметана і Зелень", brand: "Lays", quantity: 17 },
	{ id: 50, name: "Шампунь Проти Лупи", brand: "Head&Shoulders", quantity: 16 },
 ];
 